// client/src/routes/cover-letter/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
    import Button from '$components/ui/Button.svelte';
    import Spinner from '$components/ui/Spinner.svelte';
    import Alert from '$components/ui/Alert.svelte';
    import FormField from '$components/forms/FormField.svelte';
    import FormArea from '$components/forms/FormArea.svelte';
    import FormDropdown from '$components/forms/FormDropdown.svelte';
    import { authStore } from '$stores/auth';
    import { api } from '$lib/api/client';
    import type { CoverLetterType, ResumeType } from '$lib/types';

    let userResumes: ResumeType[] = [];
    let isLoading = false;
    let errorMessage = '';
    let showSaveMessage = false;
    let inputMode: 'manual' | 'link' = 'manual';
    let jobUrl = '';

    let coverLetter: CoverLetterType = {
        _id: '',
        letter: '',
        name: '',
        date: new Date(),
        jobDescription: '',
        jobTitle: '',
        city: '',
        state: '',
        company: '',
        resumeId: '',
    };

    async function loadCoverLetter(id: string) {
        try {
            const response = await api.get<{ coverLetter: CoverLetterType }>(`/cover-letter/${id}`);
            return response.coverLetter;
        } catch {
            console.error('Error loading cover letter');
        }
        return null;
    }

    async function loadResumes(userId: string) {
        try {
            const response = await api.get<{ resumes: ResumeType[] }>(`/resume/user?userId=${userId}`);
            const resumesIn = response.resumes;

            if (resumesIn && resumesIn.length > 0) {
                userResumes = resumesIn;
                return resumesIn[0]._id;
            } else {
                userResumes = [];
                return null;
            }
        } catch {
            console.error('Error loading resumes');
            return null;
        }
    }

    onMount(async () => {
        const user = $authStore.user;
        if (!user) {
            authStore.openAuthModal();
            return;
        }

        let newCoverLetter = { ...coverLetter };

        // Check if editing existing cover letter
        const urlParams = new URLSearchParams(window.location.search);
        const id = urlParams.get('id');
        if (id) {
            const loaded = await loadCoverLetter(id);
            if (loaded) {
                newCoverLetter = { ...loaded, _id: id };
            }
        }

        // Set default name and load resumes
        if (newCoverLetter.name === '') {
            newCoverLetter.name = user.fullName || 'Your Name';
        }

        const resumeId = await loadResumes(user.id);
        if (resumeId && !newCoverLetter.resumeId) {
            newCoverLetter.resumeId = resumeId;
        }

        coverLetter = newCoverLetter;
    });

    async function handleGenerateCoverLetter() {
        const user = $authStore.user;
        if (!user) {
            errorMessage = 'User not found';
            return;
        }

        try {
            isLoading = true;
            errorMessage = '';

            const payload: Record<string, unknown> = { clerkId: user.id };
            if (inputMode === 'link') {
                payload.coverLetter = { ...coverLetter, jobUrl, useJobUrl: true };
            } else {
                payload.coverLetter = { ...coverLetter, useJobUrl: false };
            }

            const response = await api.post<{ coverLetter: CoverLetterType }>('/cover-letter', payload);
            coverLetter = response.coverLetter;
        } catch (error: unknown) {
            console.error(error);
            const err = error as { status?: number; code?: string };
            if (inputMode === 'link' && (err.status === 400 || err.code === 'URL_PARSE_ERROR')) {
                errorMessage = 'Failed to load job, please enter manually or try again later';
                inputMode = 'manual';
            } else {
                errorMessage = 'An error occurred while generating cover letter';
            }
        } finally {
            isLoading = false;
        }
    }

    async function handleSaveCoverLetter(exit: boolean) {
        const user = $authStore.user;
        if (!user) {
            errorMessage = 'User not found';
            return;
        }

        try {
            isLoading = true;
            const response = await api.put<{ coverLetter: CoverLetterType }>(`/cover-letter/${coverLetter._id}`, coverLetter);
            coverLetter = response.coverLetter;
            showSaveMessage = true;
            setTimeout(() => (showSaveMessage = false), 2000);

            if (exit) {
                goto('/dashboard');
            }
        } catch {
            console.error('Error saving cover letter');
            errorMessage = 'Failed to save cover letter';
        } finally {
            isLoading = false;
        }
    }

    function handlePrint() {
        window.print();
    }

    function formatDate(date: Date | string): string {
        const d = new Date(date);
        return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    }

    function handleResumeSelect(e: CustomEvent<string>) {
        const selectedResume = userResumes.find(res => res.name === e.detail);
        if (selectedResume) {
            coverLetter.resumeId = selectedResume._id;
        }
    }
</script>

<svelte:head>
    <title>Cover Letter Generator - ResumeTitan</title>
</svelte:head>

<div class="page-container bg-white min-h-screen">
    <div class="flex flex-col lg:flex-row p-4 gap-8">
        <!-- Form Section -->
        <div class="flex-1 w-full">
            <div class="flex justify-center w-full">
                <div class="form-container mt-1 max-w-lg w-full">
                    <div class="form-text-main mb-4">Cover Letter Information</div>

                    <!-- Profile Info Section -->
                    <div class="mb-6 p-4 rounded bg-gray-50 border border-gray-200">
                        <div class="font-bold mb-2">Profile Information</div>
                        <FormField id="name" label="Name" bind:value={coverLetter.name} />
                        <div class="grid grid-cols-2 gap-4">
                            <FormField id="city" label="City" bind:value={coverLetter.city} />
                            <FormField id="state" label="State" bind:value={coverLetter.state} />
                        </div>
                    </div>

                    <!-- AI Input Section -->
                    <div class="mb-6 p-4 rounded bg-white border border-gray-200">
                        <div class="font-bold mb-2">Job Information for AI</div>

                        <!-- Tab buttons -->
                        <div class="flex mb-4 gap-0.5">
                            <button
                                type="button"
                                class="flex-1 py-1.5 rounded-t-lg font-bold text-lg transition-colors {inputMode === 'manual'
                                    ? 'bg-main-green text-white'
                                    : 'bg-gray-200 text-main-green'}"
                                on:click={() => (inputMode = 'manual')}
                            >
                                Job Title/Description
                            </button>
                            <button
                                type="button"
                                class="flex-1 py-1.5 rounded-t-lg font-bold text-lg transition-colors {inputMode === 'link'
                                    ? 'bg-main-green text-white'
                                    : 'bg-gray-200 text-main-green'}"
                                on:click={() => (inputMode = 'link')}
                            >
                                Job URL
                            </button>
                        </div>

                        <!-- Error Message -->
                        {#if errorMessage}
                            <Alert variant="error" dismissible onDismiss={() => (errorMessage = '')}>
                                {errorMessage}
                            </Alert>
                        {/if}

                        {#if inputMode === 'manual'}
                            <FormField id="jobTitle" label="Job Title" bind:value={coverLetter.jobTitle} />
                            <FormField id="company" label="Company" bind:value={coverLetter.company} />
                            <FormArea id="jobDescription" label="Job Description" bind:value={coverLetter.jobDescription} />
                        {:else}
                            <FormField
                                id="jobUrl"
                                label="Job Posting URL"
                                bind:value={jobUrl}
                                placeholder="Paste the job posting link here..."
                            />
                        {/if}

                        {#if userResumes && userResumes.length > 0}
                            <FormDropdown
                                id="resume"
                                label="Select Resume"
                                value={userResumes.find(r => r._id === coverLetter.resumeId)?.name || ''}
                                options={userResumes.map(resume => ({
                                    value: resume.name,
                                    label: resume.name,
                                }))}
                                on:change={handleResumeSelect}
                            />
                        {/if}
                    </div>

                    {#if coverLetter.letter}
                        <FormArea id="letter" label="Cover Letter" bind:value={coverLetter.letter} rows={15} />
                    {/if}

                    <div class="p-4 space-y-3">
                        <Button variant="primary" fullWidth on:click={handleGenerateCoverLetter}>
                            {isLoading ? 'Writing...' : 'Write Cover Letter with AI'}
                        </Button>

                        {#if coverLetter.letter}
                            <Button variant="secondary" fullWidth on:click={handlePrint}>Print / Download PDF</Button>

                            <Button variant="secondary" fullWidth on:click={() => handleSaveCoverLetter(false)}>Save Cover Letter</Button>

                            <Button variant="primary" fullWidth on:click={() => handleSaveCoverLetter(true)}>Save and Exit</Button>
                        {/if}
                    </div>

                    {#if showSaveMessage}
                        <div
                            class="fixed top-8 left-1/2 transform -translate-x-1/2 bg-white text-dark-green px-6 py-3 rounded text-base whitespace-nowrap animate-fade-in-out border border-dark-green z-50 shadow-lg font-semibold"
                        >
                            Cover Letter Saved!
                        </div>
                    {/if}
                </div>
            </div>
        </div>

        <!-- Cover Letter Preview -->
        <div class="lg:ml-8 flex items-start justify-center print:ml-0">
            <div
                id="print-root"
                class="cover-letter-container w-[8.5in] max-w-[8.5in] border border-gray-300 shadow-md bg-white p-2.5 print:border-0 print:shadow-none"
            >
                <div class="p-5 font-serif">
                    <p>{coverLetter.name}</p>
                    <p>{`${coverLetter.city || '[City]'}, ${coverLetter.state || '[State]'}`}</p>
                    <p>{formatDate(coverLetter.date)}</p>
                    <br />
                    <p>{coverLetter.jobTitle || '[Job Title]'}</p>
                    <p>{coverLetter.company || '[Company Name]'}</p>
                    <br />
                    {#if coverLetter.letter}
                        {#each coverLetter.letter.split('\n') as paragraph}
                            <p>{paragraph.trim() !== '' ? paragraph : '\u00A0'}</p>
                        {/each}
                    {/if}
                </div>
            </div>
        </div>
    </div>

    {#if isLoading}
        <Spinner />
    {/if}
</div>

<style>
    @media print {
        :global(body *) {
            display: none !important;
        }
        #print-root,
        #print-root * {
            display: block !important;
            position: static !important;
            width: 100% !important;
            box-shadow: none !important;
            background: white !important;
            color: black !important;
            transform: none !important;
        }
    }
</style>

// client/src/pages/coverLetter/index.tsx
import React, { useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useUser } from '@clerk/clerk-react';
import Spinner from 'components/Spinner';
import api, { setTokenFunction } from 'api/actions';
import CoverLetterTemplate from './CoverLetterHolder';
import { FormContainer } from 'components/Form/styled';
import FormField from 'components/Form/FormField';
import FormArea from 'components/Form/FormArea';
import FormDropdown from 'components/Form/FormDropdown';
import { useAuth } from '@clerk/clerk-react';
import 'styles/index.css';
import { CoverLetterType, ResumeType } from 'types/types';
import styled, { createGlobalStyle } from 'styled-components';
import { PDFDownloadLink, BlobProviderParams } from '@react-pdf/renderer';
import CoverLetterPDF from './CoverLetterPDF';

const Container = styled.div`
  background-color: white;
  color: black; /* Change to your desired text color */
  display: flex;
  flex-direction: row; /* default: row */
  padding: 1rem;

  @media (max-width: 1200px) {
    flex-direction: column; /* on small screens, stack (cover letter below forms) */
    padding: 1rem;
  }
`;

const ResponsiveFormContainer = styled.div`
  max-width: 500px;
  width: 100%;
  margin: 0 auto;
  box-sizing: border-box;
  @media (max-width: 1200px) {
    max-width: 100%;
    width: 100%;
    margin-top: 1rem;
  }
`;

// Add a styled wrapper for the cover letter preview
const CoverLetterPreviewWrapper = styled.div`
  margin-left: 2rem;
  display: flex;
  align-items: flex-start;
  @media (max-width: 1200px) {
    margin-left: 0;
    margin-top: 1rem;
    justify-content: center;
    /* Scale down the cover letter for small screens */
    & > * {
      transform: scale(1);
      transform-origin: top center;
    }
  }
  @media (max-width: 600px) {
    & > * {
      transform: scale(0.8);
    }
  }
`;

const PrintOnlyCoverLetter = createGlobalStyle`
  @media print {
    body * {
      display: none !important;
    }
    #print-root, #print-root * {
      display: block !important;
      position: static !important;
      width: 100% !important;
      box-shadow: none !important;
      background: white !important;
      color: black !important;
      transform: none !important;
    }
  }
`;

const CoverLetter: React.FC = () => {
  const { user, isSignedIn } = useUser();
  const { getToken } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [userResumes, setUserResumes] = React.useState([]);
  const [isLoading, setIsLoading] = React.useState(false);
  const [coverLetter, setCoverLetter] = React.useState<CoverLetterType>({
    _id: '',
    letter: '',
    name: '',
    date: new Date(),
    jobDescription: '',
    jobTitle: '',
    city: '',
    state: '',
    company: '',
    resumeId: ''
  });
  const [inputMode, setInputMode] = React.useState<'manual' | 'link'>('manual');
  const [jobUrl, setJobUrl] = React.useState('');
  const [showSaveMessage, setShowSaveMessage] = React.useState(false);
  const coverLetterRef = useRef<HTMLDivElement>(null);

  // Set up the token function for API calls
  React.useEffect(() => {
    setTokenFunction(getToken);
  }, [getToken]);

  /**
   * @function loadCoverLetter
   */
  const loadCoverLetter = async (id: string) => {
    const response = await api.get(`/cover-letter/${id}`);
    if (response.status !== 404) {
      return response.data.coverLetter;
    }
  }

  /**
   * @function loadResumes
   */
  const loadResumes = async (id: string) => {
    const response = await api.get(`/resume/user?userId=${id}`);
    const resumesIn = response.data.resumes;

    if (resumesIn.length >= 0) {
      setUserResumes(resumesIn);
      return resumesIn[0]._id;
    } else {
      return 0;
    }
  }

  /**
   * @function useEffect
   * @description Called when page loads
   */
  React.useEffect(() => {
    async function load() {
      let newCoverLetter = coverLetter;
      if (location.state) {
        const id = location.state.id;
        newCoverLetter = await loadCoverLetter(id);
        newCoverLetter["_id"] = id;
      }

      if (user) {
        if (newCoverLetter.name === '') {
          newCoverLetter["name"] = user.fullName || 'Your Name';
        }
        const resumeId = await loadResumes(user.id);
        newCoverLetter["resumeId"] = resumeId;
      }

      setCoverLetter(newCoverLetter);
    }

    load();
  }, [user]);

  /**
   * @function handleGenerateCoverLetter
   * @description Call AI to generate cover letter
   */
  const handleGenerateCoverLetter = async () => {
    try {
      if (!user) {
        throw new Error("User not found");
      }
      setIsLoading(true);
      let payload: any = { clerkId: user.id };
      if (inputMode === 'link') {
        payload.coverLetter = { ...coverLetter, jobUrl, useJobUrl: true };
      } else {
        payload.coverLetter = { ...coverLetter, useJobUrl: false };
      }
      const response = await api.post("cover-letter", payload);
      setCoverLetter(response.data.coverLetter);
      setIsLoading(false);
    } catch (error) {
      console.error(error);
    }
  }

  const handleSaveCoverLetter = async (exit: boolean) => {
    try {
      if (!user) {
        throw new Error("User not found");
      }
      setIsLoading(true);
      let payload: any = { clerkId: user.id };
      if (inputMode === 'link') {
        payload.coverLetter = { ...coverLetter, jobUrl, useJobUrl: true };
      } else {
        payload.coverLetter = { ...coverLetter, useJobUrl: false };
      }
      const response = await api.put(`cover-letter/${coverLetter._id}`, payload);
      setCoverLetter(response.data.coverLetter);
      setIsLoading(false);
      setShowSaveMessage(true);
      setTimeout(() => setShowSaveMessage(false), 2000);
      if (exit) {
        navigate("/dashboard");
      }
    } catch (error) {
      console.error(error);
    }
  }

  // Custom tab button style
  const tabButtonStyle = (active: boolean) => ({
    flex: 1,
    padding: '6px 0',
    borderRadius: '8px 8px 0 0',
    fontWeight: 'bold',
    fontSize: '1.1rem',
    background: active ? '#115E59' : '#e2e8f0',
    color: active ? 'white' : '#115E59',
    border: 'none',
    outline: 'none',
    cursor: 'pointer',
    transition: 'background 0.2s, color 0.2s',
  });

  if (!user) {
    return null;
  }

  return (
    <Container>
      <div style={{ flex: 1, width: '100%' }}>
        <div style={{ display: 'flex', justifyContent: 'center', width: '100%' }}>
          <ResponsiveFormContainer className="form-container">
            <div className="form-text-main mb-4">
              Cover Letter Information
            </div>
            {/* Profile Info Section */}
            <div className="mb-6 p-4 rounded bg-gray-50 border border-gray-200">
              <div className="font-bold mb-2">Profile Information</div>
              <FormField 
                title={"Name"}
                value={coverLetter.name}
                onChange={(event) => setCoverLetter({...coverLetter, name: event.target.value})}
              />
              <FormField 
                title={"Email"}
                value={user?.emailAddresses?.[0]?.toString() || ''}
                onChange={() => {}}
                disabled
              />
              <FormContainer>
                <FormField 
                  title={"City"}
                  value={coverLetter.city}
                  onChange={(event) => {setCoverLetter({...coverLetter, city: event.target.value})}}
                />
                <FormField 
                  title={"State"}
                  value={coverLetter.state}
                  onChange={(event) => {setCoverLetter({...coverLetter, state: event.target.value})}}
                />
              </FormContainer>
            </div>

            {/* AI Input Section */}
            <div className="mb-6 p-4 rounded bg-white border border-gray-200">
              <div className="font-bold mb-2">Job Information for AI</div>
              <div style={{ display: 'flex', marginBottom: 16, gap: 2 }}>
                <button
                  style={tabButtonStyle(inputMode === 'manual')}
                  onClick={() => setInputMode('manual')}
                  type="button"
                >
                  Job Title/Description
                </button>
                <button
                  style={tabButtonStyle(inputMode === 'link')}
                  onClick={() => setInputMode('link')}
                  type="button"
                >
                  Job URL
                </button>
              </div>
              {inputMode === 'manual' ? (
                <>
                  <FormField 
                    title={"Job Title"}
                    value={coverLetter.jobTitle}
                    onChange={(event) => setCoverLetter({...coverLetter, jobTitle: event.target.value})}
                  />
                  <FormField 
                    title={"Company"}
                    value={coverLetter.company}
                    onChange={(event) => setCoverLetter({...coverLetter, company: event.target.value})}
                  />
                  <FormArea 
                    title={"Job Description"}
                    value={coverLetter.jobDescription}
                    onChange={(event) => setCoverLetter({...coverLetter, jobDescription: event.target.value})}
                  />
                </>
              ) : (
                <>
                  <FormField 
                    title={"Job Posting URL"}
                    value={jobUrl}
                    onChange={(event) => setJobUrl(event.target.value)}
                    placeholder="Paste the job posting link here..."
                  />
                </>
              )}
              <FormDropdown 
                title={"Select Resume"}
                onChange={(event) => {
                  const resumeId = userResumes.find((res: ResumeType) => res.name === event.target.value);
                  if (resumeId) {
                    setCoverLetter({...coverLetter, resumeId})}
                  }
                }
              >
                {userResumes && userResumes.map((resume: any) => (
                  <option value={resume.id}>{resume.name}</option>
                ))}
              </FormDropdown>
            </div>

            {coverLetter.letter && (
              <FormArea 
                title={"Cover Letter"}
                value={coverLetter.letter}
                rows={10}
                onChange={(event) => setCoverLetter({...coverLetter, letter: event.target.value})}
              />
            )}
            <div className="p-4">
              <button
                className="interview-button"
                onClick={handleGenerateCoverLetter}
              >
                {isLoading ? 'Writing...' : 'Write Cover Letter with AI'}
              </button>
              <button>
                <PDFDownloadLink
                  document={<CoverLetterPDF coverLetter={coverLetter} />}
                  fileName="cover-letter.pdf"
                >
                  {/* @ts-ignore */}
                  {({ loading }) => (
                    <button
                      className="interview-button"
                      style={{ marginTop: '1rem' }}
                    >
                      {loading ? 'Preparing PDF...' : 'Download PDF'}
                    </button>
                  )}
                </PDFDownloadLink>
              </button>

              {coverLetter.letter && (
                <button
                  className="interview-button"
                  onClick={() => handleSaveCoverLetter(false)}
                >
                  {"Save Cover Letter"}
                </button>
              )}
              {coverLetter.letter && (
                <button
                  className="interview-button"
                  onClick={() => handleSaveCoverLetter(true)}
                >
                  {"Save and Exit"}
                </button>
              )}
              {showSaveMessage && (
                <div className="fixed top-8 left-1/2 transform -translate-x-1/2 bg-white text-dark-green px-6 py-3 rounded text-base whitespace-nowrap animate-fade-in-out border border-dark-green z-50 shadow-lg font-semibold">
                  Cover Letter Saved!
                </div>
              )}
            </div>
          </ResponsiveFormContainer>
        </div>
      </div>

      <CoverLetterPreviewWrapper id="print-root" ref={coverLetterRef}>
        <CoverLetterTemplate coverLetter={coverLetter} />
      </CoverLetterPreviewWrapper>

      <PrintOnlyCoverLetter />

      { isLoading && (
        <Spinner />
      )}

    </Container>
  );
};

export default CoverLetter;
