// client/src/lib/components/resume/templates/onepage/Resume.svelte
<script lang="ts">
	import type { ResumeType } from '$types';
	import { formatDateRange } from '$utils';

	export let resume: ResumeType;

	$: basics = resume.basics;
	$: sections = resume.sections || [];

	function shouldShowSection(sectionName: string): boolean {
		return sections.includes(sectionName);
	}
</script>

<div class="onepage-resume p-6 max-w-[660px] mx-auto">
	<!-- Header -->
	{#if shouldShowSection('Basics')}
		<header class="mb-4">
			<h1 class="text-xl font-bold">{basics.name || 'Your Name'}</h1>
			<div class="flex flex-wrap gap-2 text-xs text-gray-600 mt-1">
				{#if basics.email}<span>{basics.email}</span>{/if}
				{#if basics.phone}<span>• {basics.phone}</span>{/if}
				{#if basics.location?.city}
					<span>• {basics.location.city}{basics.location.region ? `, ${basics.location.region}` : ''}</span>
				{/if}
			</div>
		</header>
	{/if}

	<!-- Summary -->
	{#if shouldShowSection('Summary') && basics.summary}
		<section class="mb-3 pb-3 border-b border-dashed border-[#cfcfcf]">
			<p class="text-xs">{basics.summary}</p>
		</section>
	{/if}

	<!-- Experience -->
	{#if shouldShowSection('Work') && resume.work && resume.work.length > 0}
		<section class="mb-3 pb-3 border-b border-dashed border-[#cfcfcf]">
			<h2 class="text-sm font-bold mb-2">Experience</h2>
			{#each resume.work as job}
				<div class="mb-2">
					<div class="flex justify-between text-xs">
						<span class="font-medium">{job.position} at {job.name}</span>
						<span class="text-gray-500">{formatDateRange(job.startDate, job.endDate, job.endDateCurrent)}</span>
					</div>
					{#if job.highlights && job.highlights.length > 0}
						<ul class="list-disc list-inside text-xs mt-1 text-gray-700">
							{#each job.highlights.slice(0, 3) as highlight}
								{#if highlight}<li>{highlight}</li>{/if}
							{/each}
						</ul>
					{/if}
				</div>
			{/each}
		</section>
	{/if}

	<!-- Education -->
	{#if shouldShowSection('Education') && resume.education && resume.education.length > 0}
		<section class="mb-3 pb-3 border-b border-dashed border-[#cfcfcf]">
			<h2 class="text-sm font-bold mb-2">Education</h2>
			{#each resume.education as edu}
				<div class="flex justify-between text-xs mb-1">
					<span>
						<span class="font-medium">{edu.institution}</span> -
						{edu.studyType}{edu.area ? ` in ${edu.area}` : ''}
					</span>
					<span class="text-gray-500">{formatDateRange(edu.startDate, edu.endDate, edu.endDateCurrent)}</span>
				</div>
			{/each}
		</section>
	{/if}

	<!-- Skills -->
	{#if shouldShowSection('Skills') && resume.skills && resume.skills.length > 0}
		<section class="mb-3">
			<h2 class="text-sm font-bold mb-2">Skills</h2>
			<div class="text-xs">
				{#each resume.skills as skill}
					<span class="inline-block mr-3 mb-1">
						<span class="font-medium">{skill.name}:</span> {skill.keywords?.join(', ')}
					</span>
				{/each}
			</div>
		</section>
	{/if}
</div>

<style>
	.onepage-resume {
		font-size: 11px;
		line-height: 1.4;
	}
</style>

// client/src/templates/layouts/meyer/Resume.tsx
import React from 'react';
import { ResumeType } from 'types/types';
import styled from 'styled-components';
import { formatDate } from '../../../utils';

const Container = styled.div`
  background: white;
  padding: 10mm 12mm 8mm 12mm;
  width: 100%;
  height: 100%;
  font-family: 'Georgia', 'Times New Roman', Times, serif;
  color: #222;
  box-sizing: border-box;
  overflow: hidden;
  font-size: 10pt;
  line-height: 1.2;
`;

const Name = styled.div`
  font-size: 20pt;
  font-weight: bold;
  text-align: center;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  margin-bottom: 1mm;
  line-height: 1.1;
`;

const Contact = styled.div`
  text-align: center;
  font-size: 10pt;
  margin-bottom: 4mm;
  line-height: 1.2;
`;

const Section = styled.div`
  margin-top: 4mm;
`;

const SectionTitle = styled.div`
  font-size: 12pt;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  margin-bottom: 2mm;
  border-bottom: 1pt solid #222;
  padding-bottom: 1mm;
  line-height: 1.2;
`;

const JobHeader = styled.div`
  display: flex;
  justify-content: space-between;
  font-weight: bold;
  font-size: 11pt;
  margin-bottom: 1mm;
  line-height: 1.2;
`;

const JobSubHeader = styled.div`
  display: flex;
  justify-content: space-between;
  font-style: italic;
  font-size: 10pt;
  margin-bottom: 1mm;
  line-height: 1.2;
`;

const Bullets = styled.ul`
  margin: 1mm 0 1mm 3mm;
  padding: 0;
  list-style-type: disc;
`;

const Bullet = styled.li`
  margin-bottom: 1mm;
  font-size: 9pt;
  line-height: 1.3;
`;

const Small = styled.span`
  font-size: 9pt;
  line-height: 1.2;
`;

const SkillsSection = styled.div`
  font-size: 9pt;
  line-height: 1.3;
  margin-bottom: 1mm;
`;

const MeyerResume: React.FC<{ resume: ResumeType }> = ({ resume }) => {
  const { basics, work = [], education = [], skills = [], awards = [], volunteer = [], sections = [] } = resume;

  return (
    <Container>
      <Name>{basics?.name || 'Your Name'}</Name>
      <Contact>
        {basics?.email} {basics?.phone && <>| {basics.phone}</>} {basics?.url && <>| {basics.url}</>}
        {basics?.profiles && basics.profiles[0]?.url && <> | {basics.profiles[0].url}</>}
        {basics?.location && basics?.location.city && basics?.location.region && <> | {basics.location.city}, {basics.location.region}</>}
      </Contact>

      {/* Professional Experience */}
      <Section>
        <SectionTitle>Professional Experience</SectionTitle>
        {work.map((job, i) => (
          <div key={i}>
            <JobHeader>
              <span>{job.name}</span>
            </JobHeader>
            <JobSubHeader>
              <span>{job.position}</span>
              <span>
                {job.startDate ? ` ${formatDate(job.startDate)}` : ''} {job.endDate ? ` - ${formatDate(job.endDate)}` : ''}
              </span>
            </JobSubHeader>
            {job.highlights && job.highlights.length > 0 && (
              <Bullets>
                {job.highlights.map((hl, j) => (
                  <Bullet key={j}>{hl}</Bullet>
                ))}
              </Bullets>
            )}
          </div>
        ))}
      </Section>

      {/* Education */}
      <Section>
        <SectionTitle>Education</SectionTitle>
        {education.map((edu, i) => (
          <div key={i}>
            <JobHeader>
              <span>{edu.institution}</span>
            </JobHeader>
            <JobSubHeader>
              <span>{edu.studyType} {edu.area && <>in {edu.area}</>} </span>
              <span>{edu.endDate ? `Graduated ${formatDate(edu.endDate)}` : ''}</span>
            </JobSubHeader>
            {edu.score && <Small>GPA: {edu.score}</Small>}
            {edu.highlights && edu.highlights.length > 0 && (
              <Bullets>
                {edu.highlights.map((hl, j) => (
                  <Bullet key={j}>{hl}</Bullet>
                ))}
              </Bullets>
            )}
          </div>
        ))}
      </Section>

      {/* Skills*/}
      <Section>
        <SectionTitle>Skills</SectionTitle>
        {skills.map((skill, index) => (
          <SkillsSection key={index}>
            <b>{skill.name}{skill.keywords.length > 0 ? ':' : ''}</b> {skill.keywords && skill.keywords.length > 0 ? skill.keywords.join(', ') : ''}
          </SkillsSection>
        ))}
      </Section>
    </Container>
  );
};

export default MeyerResume;
