// client/src/lib/components/resume/ResumeContainer.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { ResumeType } from '$types';
	import { getFontFamily } from '$utils';
	import { RESUME_CONFIG } from '$config';

	// Template imports
	import ProfessionalResume from './templates/professional/Resume.svelte';
	import MacchiatoResume from './templates/macchiato/Resume.svelte';
	import StrattonResume from './templates/stratton/Resume.svelte';
	import OnepageResume from './templates/onepage/Resume.svelte';
	import StudentClassicResume from './templates/studentClassic/Resume.svelte';
	import AcademicModernResume from './templates/academicModern/Resume.svelte';

	export let resume: ResumeType;
	export let scale = 1;
	export let autoScale = true;

	let containerElement: HTMLDivElement;
	let contentElement: HTMLDivElement;
	let calculatedScale = 1;

	const templates: Record<string, typeof ProfessionalResume> = {
		professional: ProfessionalResume,
		harvard: ProfessionalResume, // Uses same template
		macchiato: MacchiatoResume,
		stratton: StrattonResume,
		onepage: OnepageResume,
		'student-classic': StudentClassicResume,
		'academic-modern': AcademicModernResume
	};

	$: CurrentTemplate = templates[resume.theme] || ProfessionalResume;
	$: fontFamily = getFontFamily(resume.font);
	$: themeClass = `theme-${resume.theme}`;

	// Calculate scale based on container width
	function calculateScale() {
		if (!autoScale || !containerElement || !contentElement) return;

		const containerWidth = containerElement.clientWidth;
		const pageWidth = RESUME_CONFIG.A4_WIDTH_MM * 3.7795275591; // mm to px (96 dpi)

		const newScale = Math.min(containerWidth / pageWidth, 1);
		calculatedScale = Math.max(newScale, RESUME_CONFIG.MIN_SCALE);
	}

	onMount(() => {
		if (autoScale) {
			calculateScale();

			const resizeObserver = new ResizeObserver(() => {
				calculateScale();
			});

			if (containerElement) {
				resizeObserver.observe(containerElement);
			}

			return () => {
				resizeObserver.disconnect();
			};
		}
	});

	$: effectiveScale = autoScale ? calculatedScale : scale;
</script>

<div
	bind:this={containerElement}
	class="resume-container-wrapper w-full flex justify-center overflow-hidden"
>
	<div
		bind:this={contentElement}
		class="resume-container {themeClass} bg-white shadow-lg"
		style="
			font-family: {fontFamily};
			transform: scale({effectiveScale});
			transform-origin: top center;
			width: {RESUME_CONFIG.A4_WIDTH_MM}mm;
			min-height: {RESUME_CONFIG.A4_HEIGHT_MM}mm;
		"
	>
		<svelte:component this={CurrentTemplate} {resume} />
	</div>
</div>

<style>
	.resume-container {
		background: white;
		color: black;
		line-height: 1.4;
	}

	@media print {
		.resume-container-wrapper {
			overflow: visible;
		}

		.resume-container {
			transform: none !important;
			box-shadow: none !important;
			width: 210mm !important;
			min-height: 297mm !important;
		}
	}
</style>

// client/src/templates/ResumeContainer.tsx
import React, { forwardRef, useEffect } from 'react';
import OnePageResume from './layouts/onepage';
import ProfessionalResume from './layouts/professional/Resume';
import MacchiatoResume from './layouts/macchiato/Resume';
import StudentClassicResume from './layouts/studentClassic/StudentClassicResume';
import AcademicModernResume from './layouts/academicModern/AcademicModernResume';
import { ResumeTypeProps } from 'types/types';
import styled from 'styled-components';

interface ScaledContainerProps {
  $scale?: number;
}

interface ResumeContainerProps extends ResumeTypeProps {
  onOverflowChange?: (hasOverflow: boolean) => void;
}

const StyledContainer = styled.div`
  width: 210mm;
  height: 297mm;
  background-color: white;
  margin: 0 auto;
  position: relative;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  overflow: hidden;

  @media print {
    box-shadow: none;
    width: 210mm;
    height: 297mm;
  }
`;

const ScaledContainer = styled.div<ScaledContainerProps>`
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px;
  overflow: auto;

  @media screen {
    & > ${StyledContainer} {
      transform-origin: top left;
      transform: scale(${props => props.$scale || 1});
    }
  }

  @media print {
    padding: 0;
    overflow: visible;
    
    & > ${StyledContainer} {
      transform: none;
      width: 210mm;
      height: 297mm;
    }
  }
`;

const ResumeContainer = forwardRef<HTMLDivElement, ResumeContainerProps>(({ resume, onOverflowChange }, ref) => {
  // Calculate scale based on container width
  const [scale, setScale] = React.useState(1);
  const containerRef = React.useRef<HTMLDivElement>(null);

  // Check for content overflow
  useEffect(() => {
    const checkOverflow = () => {
      if (ref && 'current' in ref && ref.current) {
        const contentHeight = ref.current.scrollHeight;
        const containerHeight = ref.current.clientHeight;
        const hasOverflow = contentHeight > containerHeight;
        
        if (onOverflowChange) {
          onOverflowChange(hasOverflow);
        }
      }
    };

    // Check overflow after initial render and on content changes
    checkOverflow();
    
    // Set up a ResizeObserver to check for overflow when content changes
    const resizeObserver = new ResizeObserver(checkOverflow);
    if (ref && 'current' in ref && ref.current) {
      resizeObserver.observe(ref.current);
    }

    return () => {
      resizeObserver.disconnect();
    };
  }, [resume, onOverflowChange, ref]);

  // Update scale on window resize
  useEffect(() => {
    const updateScale = () => {
      if (containerRef.current) {
        const containerWidth = containerRef.current.clientWidth - 40; // Account for padding
        const scale = containerWidth / 210; // 210mm is A4 width
        setScale(Math.min(scale, 1)); // Don't scale up, only down
      }
    };

    updateScale();
    window.addEventListener('resize', updateScale);
    return () => window.removeEventListener('resize', updateScale);
  }, []);

  return (
    <ScaledContainer ref={containerRef} $scale={scale}>
      <StyledContainer ref={ref}>
        {resume.theme === "harvard" && <ProfessionalResume resume={resume} />}
        {resume.theme === "one-page" && <OnePageResume resume={resume} />}
        {resume.theme === "professional" && <ProfessionalResume resume={resume} />}
        {resume.theme === "macchiato" && <MacchiatoResume resume={resume} />}
        {resume.theme === "student-classic" && <StudentClassicResume resume={resume} />}
        {resume.theme === "academic-modern" && <AcademicModernResume resume={resume} />}
        {/* Default */}
        {resume.theme === "" && <ProfessionalResume resume={resume} />}
      </StyledContainer>
    </ScaledContainer>
  );
});

ResumeContainer.displayName = 'ResumeContainer';

export default ResumeContainer;
