// client/src/components/ChatBot/ChatBot.tsx
import React, { useState, useRef, useEffect } from 'react';
import styled from 'styled-components';
import { useUser, useAuth } from '@clerk/clerk-react';
import api, { setTokenFunction } from 'api/actions';
import ChatIcon from '@mui/icons-material/Chat';
import SendIcon from '@mui/icons-material/Send';
import CloseIcon from '@mui/icons-material/Close';
import { useNavigate } from 'react-router-dom';

const ChatContainer = styled.div`
  position: fixed;
  bottom: 20px;
  right: 20px;
  width: 350px;
  height: 500px;
  background: #f8f9fa;
  border-radius: 12px;
  border: 2px solid white;
  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.3), 0 6px 12px rgba(17, 94, 89, 0.2), 0 0 0 1px rgba(17, 94, 89, 0.1);
  display: flex;
  flex-direction: column;
  z-index: 1000;
  backdrop-filter: blur(10px);
  animation: slideInUp 0.3s ease-out;

  @keyframes slideInUp {
    from {
      transform: translateY(20px);
      opacity: 0;
    }
    to {
      transform: translateY(0);
      opacity: 1;
    }
  }
`;

const ChatHeader = styled.div`
  padding: 15px;
  background: #115E59;
  color: white;
  border-radius: 10px 10px 0 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-weight: bold;
  font-size: 14px;
`;

const HeaderLeft = styled.div`
  display: flex;
  align-items: center;
  gap: 10px;
`;

const CloseButton = styled.button`
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  padding: 5px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  transition: background-color 0.2s;

  &:hover {
    background-color: rgba(255, 255, 255, 0.1);
  }
`;

const ChatMessages = styled.div`
  flex: 1;
  overflow-y: auto;
  padding: 15px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  background: #ffffff;
`;

const Message = styled.div<{ $isUser: boolean }>`
  max-width: 80%;
  padding: 8px 12px;
  border-radius: 15px;
  background: ${props => props.$isUser ? '#115E59' : '#e9ecef'};
  color: ${props => props.$isUser ? 'white' : '#212529'};
  align-self: ${props => props.$isUser ? 'flex-end' : 'flex-start'};
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
  font-size: 13px;
  line-height: 1.4;
`;

const ChatInput = styled.div`
  padding: 15px;
  border-top: 1px solid #dee2e6;
  display: flex;
  flex-direction: column;
  gap: 10px;
  background: #f8f9fa;
  border-radius: 0 0 10px 10px;
`;

const InputContainer = styled.div`
  display: flex;
  gap: 10px;
`;

const Input = styled.input`
  flex: 1;
  padding: 10px;
  border: 1px solid #ced4da;
  border-radius: 20px;
  outline: none;
  font-size: 13px;
  &:focus {
    border-color: #115E59;
  }
`;

const CharCounter = styled.div`
  font-size: 10px;
  color: #6c757d;
  text-align: right;
  padding-right: 10px;
`;

const SendButton = styled.button`
  background: #115E59;
  color: white;
  border: none;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  &:hover {
    background: #0d4a45;
  }
`;

const LoginPrompt = styled.div`
  padding: 20px;
  text-align: center;
  background: #ffffff;
  border-radius: 10px;
  margin: 20px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
`;

const LoginButton = styled.button`
  background: #115E59;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
  font-weight: bold;
  margin-top: 10px;
  &:hover {
    background: #0d4a45;
  }
`;

const LoadingDots = styled.div`
  display: flex;
  gap: 4px;
  align-items: center;
`;

const LoadingDot = styled.div<{ delay: number }>`
  width: 8px;
  height: 8px;
  background: #115E59;
  border-radius: 50%;
  animation: flowWave 1.5s ease-in-out infinite;
  animation-delay: ${props => props.delay}s;

  @keyframes flow {
    0%, 60%, 100% {
      opacity: 0.3;
      transform: scale(0.8);
    }
    30% {
      opacity: 1;
      transform: scale(1.2);
    }
  }
`;

const ChatBot: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Array<{ text: string; isUser: boolean }>>([
    { 
      text: "👋 Hi! I'm your ResumeTitan Assistant. I can help you with resume writing, interview preparation, and career advice. How can I assist you today?", 
      isUser: false 
    }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const { getToken } = useAuth();
  const { isSignedIn } = useUser();
  const navigate = useNavigate();
  const MAX_CHARS = 1000;
  const MAX_RESPONSE_CHARS = 1500;
  const MAX_MESSAGES = 30;

  // Set up the token function for API calls
  useEffect(() => {
    setTokenFunction(getToken);
  }, [getToken]);

  const truncateMessage = (message: string): string => {
    if (message.length <= MAX_RESPONSE_CHARS) return message;
    return message.slice(0, MAX_RESPONSE_CHARS) + '...';
  };

  const addMessage = (text: string, isUser: boolean) => {
    setMessages(prev => {
      const newMessages = [...prev, { text, isUser }];
      if (newMessages.length > MAX_MESSAGES) {
        return newMessages.slice(-MAX_MESSAGES);
      }
      return newMessages;
    });
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim()) return;

    const userMessage = input;
    setInput('');
    addMessage(userMessage, true);
    setIsLoading(true);

    try {
      const response = await api.post('/chat', 
        { message: userMessage },
      );

      const truncatedResponse = truncateMessage(response.data.response);
      addMessage(truncatedResponse, false);
    } catch (error) {
      console.error('Error sending message:', error);
      addMessage('Sorry, I encountered an error. Please try again.', false);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleLogin = () => {
    navigate('/sign-in');
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (value.length <= MAX_CHARS) {
      setInput(value);
    }
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        style={{
          position: 'fixed',
          bottom: '20px',
          right: '20px',
          background: '#115E59',
          color: 'white',
          border: '3px solid white',
          borderRadius: '50%',
          width: '60px',
          height: '60px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
          boxShadow: '0 8px 16px rgba(0, 0, 0, 0.3), 0 4px 8px rgba(17, 94, 89, 0.3)',
          zIndex: 1000,
          transition: 'all 0.3s ease'
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.transform = 'scale(1.1)';
          e.currentTarget.style.boxShadow = '0 12px 20px rgba(0, 0, 0, 0.4), 0 6px 12px rgba(17, 94, 89, 0.4)';
          e.currentTarget.style.background = '#0d4a45';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.transform = 'scale(1)';
          e.currentTarget.style.boxShadow = '0 8px 16px rgba(0, 0, 0, 0.3), 0 4px 8px rgba(17, 94, 89, 0.3)';
          e.currentTarget.style.background = '#115E59';
        }}
      >
        <ChatIcon style={{ width: '30px', height: '30px' }} />
      </button>
    );
  }

  if (!isSignedIn) {
    return (
      <ChatContainer>
        <ChatHeader>
          <HeaderLeft>
            <ChatIcon style={{ width: '24px', height: '24px' }} />
            <span>ResumeTitan Assistant</span>
          </HeaderLeft>
          <CloseButton onClick={() => setIsOpen(false)}>
            <CloseIcon style={{ width: '20px', height: '20px' }} />
          </CloseButton>
        </ChatHeader>
        <LoginPrompt>
          <h3>Welcome to ResumeTitan Assistant!</h3>
          <p>Please sign in to use the chatbot and get personalized resume and career advice.</p>
          <LoginButton onClick={handleLogin}>Sign In</LoginButton>
        </LoginPrompt>
      </ChatContainer>
    );
  }

  return (
    <ChatContainer>
      <ChatHeader>
        <HeaderLeft>
          <ChatIcon style={{ width: '24px', height: '24px' }} />
          <span>ResumeTitan Assistant</span>
        </HeaderLeft>
        <CloseButton onClick={() => setIsOpen(false)}>
          <CloseIcon style={{ width: '20px', height: '20px' }} />
        </CloseButton>
      </ChatHeader>
      <ChatMessages>
        {messages.map((message, index) => (
          <Message key={index} $isUser={message.isUser}>
            {message.text}
          </Message>
        ))}
        {isLoading && (
          <Message $isUser={false}>
            <LoadingDots>
              <LoadingDot delay={0} />
              <LoadingDot delay={0.2} />
              <LoadingDot delay={0.4} />
            </LoadingDots>
          </Message>
        )}
        <div ref={messagesEndRef} />
      </ChatMessages>
      <ChatInput>
        <InputContainer>
          <Input
            value={input}
            onChange={handleInputChange}
            onKeyPress={handleKeyPress}
            placeholder="Type your message..."
            disabled={isLoading}
            maxLength={MAX_CHARS}
          />
          <SendButton onClick={handleSend} disabled={isLoading}>
            <SendIcon style={{ width: '20px', height: '20px' }} />
          </SendButton>
        </InputContainer>
        <CharCounter>
          {input.length}/{MAX_CHARS} characters
        </CharCounter>
      </ChatInput>
    </ChatContainer>
  );
};

export default ChatBot;

// client/src/lib/components/layout/ChatBot.svelte
<script lang="ts">
    import { fade, fly } from 'svelte/transition';
    import { chatApi } from '$api';
    import { isAuthenticated } from '$stores';
    import { CHATBOT_CONFIG } from '$config';
    import Button from '$components/ui/Button.svelte';
    import Spinner from '$components/ui/Spinner.svelte';

    interface Message {
        id: string;
        role: 'user' | 'assistant';
        content: string;
    }

    let isOpen = false;
    let input = '';
    let messages: Message[] = [];
    let loading = false;
    let messagesContainer: HTMLDivElement;

    $: canSend = input.trim().length > 0 && input.length <= CHATBOT_CONFIG.MAX_CHARS && !loading;

    function toggleChat() {
        isOpen = !isOpen;
    }

    function scrollToBottom() {
        if (messagesContainer) {
            setTimeout(() => {
                messagesContainer.scrollTop = messagesContainer.scrollHeight;
            }, 50);
        }
    }

    async function sendMessage() {
        if (!canSend) return;
        if (!$isAuthenticated) {
            messages = [
                ...messages,
                {
                    id: crypto.randomUUID(),
                    role: 'assistant',
                    content: 'Please sign in to use the AI assistant.',
                },
            ];
            return;
        }

        const userMessage: Message = {
            id: crypto.randomUUID(),
            role: 'user',
            content: input.trim(),
        };

        messages = [...messages, userMessage];
        input = '';
        loading = true;
        scrollToBottom();

        try {
            const response = await chatApi.send({
                message: userMessage.content,
                history: messages.slice(-10).map(m => ({ role: m.role, content: m.content })),
            });

            const assistantMessage: Message = {
                id: crypto.randomUUID(),
                role: 'assistant',
                content: response.response || response.message || 'Sorry, I could not process that request.',
            };

            messages = [...messages, assistantMessage];

            // Limit message history
            if (messages.length > CHATBOT_CONFIG.MAX_MESSAGES) {
                messages = messages.slice(-CHATBOT_CONFIG.MAX_MESSAGES);
            }
        } catch (error) {
            messages = [
                ...messages,
                {
                    id: crypto.randomUUID(),
                    role: 'assistant',
                    content: 'Sorry, something went wrong. Please try again.',
                },
            ];
        } finally {
            loading = false;
            scrollToBottom();
        }
    }

    function handleKeydown(event: KeyboardEvent) {
        if (event.key === 'Enter' && !event.shiftKey) {
            event.preventDefault();
            sendMessage();
        }
    }

    function clearChat() {
        messages = [];
    }
</script>

<!-- Chat Button -->
<button
    type="button"
    class="chat-bot-button fixed bottom-6 right-6 w-14 h-14 bg-main-green hover:bg-dark-green text-white rounded-full shadow-lg flex items-center justify-center transition-all z-50"
    on:click={toggleChat}
    aria-label={isOpen ? 'Close chat' : 'Open chat'}
>
    {#if isOpen}
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
    {:else}
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"
            />
        </svg>
    {/if}
</button>

<!-- Chat Window -->
{#if isOpen}
    <div
        class="fixed bottom-24 right-6 w-80 sm:w-96 bg-white rounded-lg shadow-2xl z-50 flex flex-col max-h-[70vh]"
        transition:fly={{ y: 20, duration: 200 }}
    >
        <!-- Header -->
        <div class="bg-main-green text-white px-4 py-3 rounded-t-lg flex items-center justify-between">
            <div class="flex items-center gap-2">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                    />
                </svg>
                <span class="font-medium">AI Assistant</span>
            </div>
            {#if messages.length > 0}
                <button type="button" class="text-white/80 hover:text-white text-sm" on:click={clearChat}> Clear </button>
            {/if}
        </div>

        <!-- Messages -->
        <div bind:this={messagesContainer} class="flex-1 overflow-y-auto p-4 space-y-4 min-h-[200px] max-h-[400px]">
            {#if messages.length === 0}
                <div class="text-center text-gray-500 py-8">
                    <svg class="w-12 h-12 mx-auto mb-3 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"
                        />
                    </svg>
                    <p class="text-sm">How can I help you today?</p>
                </div>
            {:else}
                {#each messages as message (message.id)}
                    <div class="flex {message.role === 'user' ? 'justify-end' : 'justify-start'}" transition:fade={{ duration: 150 }}>
                        <div
                            class="max-w-[80%] px-3 py-2 rounded-lg text-sm
								{message.role === 'user' ? 'bg-main-green text-white' : 'bg-gray-100 text-gray-800'}"
                        >
                            {message.content}
                        </div>
                    </div>
                {/each}
            {/if}

            {#if loading}
                <div class="flex justify-start">
                    <div class="bg-gray-100 px-4 py-2 rounded-lg">
                        <Spinner size="sm" />
                    </div>
                </div>
            {/if}
        </div>

        <!-- Input -->
        <div class="border-t border-gray-200 p-3">
            <div class="flex gap-2">
                <input
                    type="text"
                    bind:value={input}
                    placeholder="Ask me anything..."
                    maxlength={CHATBOT_CONFIG.MAX_CHARS}
                    class="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-main-green focus:border-transparent"
                    on:keydown={handleKeydown}
                    disabled={loading}
                />
                <Button variant="primary" size="sm" disabled={!canSend} on:click={sendMessage}>
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                    </svg>
                </Button>
            </div>
            <p class="text-xs text-gray-400 mt-1 text-right">
                {input.length}/{CHATBOT_CONFIG.MAX_CHARS}
            </p>
        </div>
    </div>
{/if}
