// client/src/components/Footer.jsx
export default function Footer() {
  return (
    <footer className="bg-main-green text-white p-2">
      <div className="w-full mx-auto max-w-screen-xl sm:p-2 p-4 md:flex md:items-center md:justify-between">
        <span className="text-md sm:text-center">&#169; ResumeTitan {new Date().getFullYear()}</span>
        <ul className="block md:flex md:flex-wrap items-center mt-3 text-sm font-medium text-gray-500 sm:mt-0 list-none">
          <li>
            <a href="/about" className="text-gray-100 pr-4">
              About Us
            </a>
          </li>
          <li>
            <a href="/terms" className="text-gray-100 pr-4">
              Terms of Service
            </a>
          </li>
          <li>
            <a href="/privacy" className="text-gray-100 pr-4">
              Privacy Policy
            </a>
          </li>
          <li>
            <a href="/contact" className="text-gray-100 pr-4">
              Contact Us
            </a>
          </li>
          <li>
            <a href="/survey" className="text-gray-100">
              Have Feedback?
            </a>
          </li>
        </ul>
        </div>
    </footer>
  );
}

// client/src/lib/components/layout/Footer.svelte
<script lang="ts">
	import { authStore } from '$stores';

	const currentYear = new Date().getFullYear();

	const footerLinks = [
		{ href: '/about', label: 'About' },
		{ href: '/contact', label: 'Contact' },
		{ href: '/privacy', label: 'Privacy Policy' },
		{ href: '/terms', label: 'Terms of Service' }
	];

	function openLogin() {
		authStore.openAuthModal();
	}
</script>

<footer class="bg-darkest-green text-white py-8 mt-auto">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
			<!-- Brand -->
			<div>
				<h3 class="text-xl font-bold mb-4">ResumeTitan</h3>
				<p class="text-gray-300 text-sm">
					AI-powered resume builder to help you land your dream job.
				</p>
			</div>

			<!-- Links -->
			<div>
				<h4 class="text-lg font-semibold mb-4">Quick Links</h4>
				<ul class="space-y-2">
					{#each footerLinks as link}
						<li>
							<a
								href={link.href}
								class="text-gray-300 hover:text-white transition-colors text-sm"
							>
								{link.label}
							</a>
						</li>
					{/each}
				</ul>
			</div>

			<!-- Contact -->
			<div>
				<h4 class="text-lg font-semibold mb-4">Get Started</h4>
				<p class="text-gray-300 text-sm mb-4">
					Create your professional resume in minutes with our AI-powered tools.
				</p>
				<button
					type="button"
					on:click={openLogin}
					class="inline-block bg-main-green hover:bg-dark-green text-white px-4 py-2 rounded-lg transition-colors text-sm"
				>
					Get Started Free
				</button>
			</div>
		</div>

		<div class="border-t border-gray-700 mt-8 pt-8 text-center text-gray-400 text-sm">
			<p>&copy; {currentYear} ResumeTitan. All rights reserved.</p>
		</div>
	</div>
</footer>
